language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
  - pip install cx_freeze wheel twine
script:
  - python setup.py bdist_wheel
  - python build.py build_exe
after_success:
  - python bintray.py
deploy:
  provider: bintray
  file: "./bintray.json"
  user: "edjubuh"
  key:
    secure: r48IUWddjka+xH1XPehopSRKC/FD6j/u2ep4W/Yw2Dm/CGwhLDEy4QKp4J3C5eHrUYW5zmwTluXDEHruGO9F8+IloClZammdh5s74Tk30fAOqUd8bTznwBeS6BsWS+yaLEGwdyFGSIrWoVt9XMIAr3hQ2UZQSsmaJxWu1QzTl5Ru4CDwUcGg8im81OtNBjF+1R3/6F9GvFnOannFz5EhUxTIlpxpuoCgDbtAEmw5BRvcwhoNZTyG6Cd0ymB4I7DbP0qUkOaxTWZE2x//Hx3DFMaTsKz+X/dctKm/YZireV8jnN25w8U1GLcNcr53gYd29bE59W3Lp3ZYJSRbp/GbWPD7a3pXxUG7IWu2JUMrzOebt1J3m7lIt1OpdcFZMRY1msV9ScFJWLCLSMyASYU+JtuIAIboTpfuAKLOkeohymmY5H00NSVlJ9PttBtnEuPj3fj2ZEbhZGpgHuyjsJMI5jQTqWLARcLNz8rL2w5yEKthR+CNQXUEm48zX6TiN1qIymbp6GOq9ULUwM4dvhP2dET4pT1mZ8zKhm4Ilgla7Pfv+vSyyUo6lbXbZWIzxL92VFXl+qoU6WDi7No86dbAygcloTHCV0nmVjkdhvuGcwP36eRn4m9ev24BW8hDQKaAmpYe3hLLDRow0zUTCXVpxgG3xNhSyb4Ps5y5sHfCMJA=
