language: python

python:
    - "3.6"

install:
    - pip install -r requirements.txt
    - pip install cx_freeze wheel twine


script:
    - python setup.py bdist_wheel
    - python build.py build_exe
