environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.0"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.0"
      PYTHON_ARCH: "64"
install:
  - "%PYTHON%\\python.exe -m pip install -r requirements"
  - "%PYTHON%\\python.exe -m pip install cx_freeze"

build_script:
  - "%PYTHON%\\python.exe build.py build_exe"

