platform:
- x86
- x64

matrix:
  - py_dir: "C:\\Python36"
  - py_dir: "C:\\Python36-x64"

matrix:
  exclude:
    - platform: x86
      py_dir: "C:\\Python36-x64"
    - platform: x64
      py_dir: ""C:\\Python36"

environment:
  PYTHON: py_dir
install:
  - "%PYTHON%\\python.exe -m pip install -r requirements"
  - "%PYTHON%\\python.exe -m pip install cx_freeze"

build_script:
  - "%PYTHON%\\python.exe build.py build_exe"

